services:
  - type: web
    name: playlist-copycat
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: SPOTIPY_CLIENT_ID
        value: 34d93772ca6b46228d0888078655c322
      - key: SPOTIPY_CLIENT_SECRET
        value: 92683941517c4daba71fbaecccc3e684
      - key: SPOTIPY_REDIRECT_URI
        value: https://playlist-copycat.onrender.com/callback